name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort
    - name: Check code formatting with black
      run: |
        black --check . || true
      continue-on-error: true
    - name: Check code formatting with isort
      run: |
        isort --check-only --diff . || true
      continue-on-error: true
    - name: Format code with black
      run: |
        black .
    - name: Format code with isort
      run: |
        isort .
    - name: Run tests
      run: pytest